### ISSUE TITLE
hardcoded the path?

### ISSUE THREAD

**Issue by haoasdasdf** [microsoft/DaVinci#1]

**Comment by haoasdasdf** [comment]
```bash
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.5-pre) Error: Assertion failed (!_src.empty()) in cv::cvtColor, file C:\Users\chenyin\Desktop\stylization\opencv-4.x\modules\imgproc\src\color.cpp, line 182
```

not only me but also others had this issue.
It seems like developers hardcoded the path? 
(Hi chenyin, please fix it thanks lol )

**Comment by hyang0511** [comment]
Sorry for this error. 

We will fix it and rebuild the executable files in the most recent release.

Best,
Huan

**Comment by hyang0511** [comment]
Hi, we have checked that this problem occurs when the executable file could not find the input image file correctly. And the hard coded path is only some debug information which does not affect the running of the toolkits. Would you please double check if the input path of the image is correct or not? Also, please make sure that your "--input" option is not a folder. It only supports file path right now.

**Comment by haoasdasdf** [comment]
Hi Huan,
Thanks for reply.

I tried again but still had the same issue.

Here is my command and logs
I think `input_video` parameter was passed
```powershell
PS C:\Users\stx\Desktop\tools\DaVinci_ISR_General_20220622> .\DaVinci_ISR_General_Tool_X4.exe --input .\2022-09-07_00-38-31.avi_20220907_010218.mp4 --output test.mp4
Please use the command as followed:
C:\Users\stx\Desktop\tools\DaVinci_ISR_General_20220622\DaVinci_ISR_General_Tool_X4.exe input output
PS C:\Users\stx\Desktop\tools\DaVinci_ISR_General_20220622>
PS C:\Users\stx\Desktop\tools\DaVinci_ISR_General_20220622> .\DaVinci_ISR_General_Tool_X2.exe .\2022-09-07_00-38-31.avi_20220907_010218.mp4 test.mp4
Selecting the fastest hardware
[0 Intel(R) HD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) HD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) HD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) HD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
Using the GPU:0
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.5-pre) Error: Assertion failed (!_src.empty()) in cv::cvtColor, file C:\Users\chenyin\Desktop\stylization\opencv-4.x\modules\imgproc\src\color.cpp, line 182
PS C:\Users\stx\Desktop\tools\DaVinci_ISR_General_20220622>
```

May I ask that do I need to pre-install the OpenCV or anything?

Best Regards,

**Comment by hyang0511** [comment]
Actually, our released executable files for ISR do not support video inputs. You may want first to decode the video into frames then use our tools to super-resolve them.

**Comment by haoasdasdf** [comment]
Hi Huan,

I see, thanks.

Best Regards
